name: livros_app
description: App de livros
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2          # gerenciar estado
  shared_preferences: ^2.3.2 # pode manter p/ favoritos não sensíveis
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  intl: ^0.19.0

  # --- ADIÇÕES p/ login seguro ---
  sqflite: ^2.3.0           # SQLite (banco robusto local)
  path: ^1.8.3              # caminho de arquivos p/ sqflite
  cryptography: ^2.5.0      # PBKDF2 (hash de senhas)
  flutter_secure_storage: ^9.0.0  # sessão segura (Keychain/Keystore)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
